version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
  
  netcat:
    container_name: netcat
    image: subfuzion/netcat
    networks:
      - testing_net 
    depends_on:
      - server
    entrypoint: sh -c "if test $(echo 'test' | nc server 12345) = 'test'; then echo 'TEST ECHO OK'; else echo 'TEST ECHO ERROR'; fi"

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
